### ISSUE TITLE
Callsim stops working after 10 seconds

### ISSUE THREAD

**Issue by FauerF** [MyPureCloud/call_simulator#1]
try to get the CallSim running. The installartion was not an issue after installing Node.JS and GIT.
Enter CallSim in the console started as an admint runs into that error after 10 seconds:

C:\Users\Administrator>callsim
Ethernet0 192.168.1.105
starting on 8888
Starting sim, interval 10
checking outbound calls current: 0 max: 10
placing call to 555
placing call to sip:555@:5060, from John Doe@sip:555-555-5555@:5060
C:\Users\Administrator\AppData\Roaming\npm\node_modules\call_simulator\node_modu
les\sip\sip.js:1338
if(hop.host === hostname) {
^

TypeError: Cannot read property 'host' of undefined
at C:\Users\Administrator\AppData\Roaming\npm\node_modules\call_simulator\no
de_modules\sip\sip.js:1338:17
at Object.send (C:\Users\Administrator\AppData\Roaming\npm\node_modules\call
simulator\nodemodules\sip\sip.js:1344:11)
at makeCallImpl (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cal
l_simulator\lib\sip_engine.js:174:13)
at Object.makeCall (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
call_simulator\lib\sip_engine.js:233:18)
at outboundCallSim (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
call_simulator\lib\simulator.js:31:23)
at Timeout.onTimeout (C:\Users\Administrator\AppData\Roaming\npm\nodemodul
es\call_simulator\lib\simulator.js:46:13)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)

C:\Users\Administrator>

Could you help me please?
Thanks
Frank

**Comment by KevinGlinski** [comment]
I'm guessing the configuration doesn't have an IP for your edge, which would be the "hostname"

**Comment by tvlemmens** [comment]
I have seen the same issues, even though the IP address was filled in. Has there been any reaction to this.

In addition, is there any documentation available, I'm having some trouble setting it up correctly. I'm running into some 408 errors during call setup.
